name: Keep Streamlit Alive

on:
  schedule:
    # Запуск каждые 12 часов (дважды в сутки - в 03:00 и 15:00 по МСК)
    - cron: '0 */12 * * *'
  workflow_dispatch: # Позволяет запускать скрипт вручную кнопкой

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Даем права на запись для создания коммита в репозиторий
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Chore: Keep-alive ping to reset Streamlit timeout"
          git push
